### ISSUE TITLE
Delete ThresholdOptedIn by using the 'PublicFlag' ...

### ISSUE THREAD

**Issue by nickurt** [TeamGnome/WUTest#10]
// Works
    .\WUDetector.exe /l:fbl_impressive /r:high

    // Don't work
    .\WUDetector.exe /l:fbl_impressive /r:high /p

    // Removed ThresholdOptedIn & works again
    .\WUDetector.exe /l:fbl_impressive /r:high /p

https://github.com/TeamGnome/WUTest/blob/master/WUTest/FlightRegistry.cs#L91-L96

**Comment by AirportsFan** [comment]
Should have been fixed now.

https://github.com/TeamGnome/WUTest/commit/78acd5ef41cefd333c84d412b28ebb08b2433178

**Comment by nickurt** [comment]
All works (Y)
