### ISSUE TITLE
Custom Win10Labs XML from Web

### ISSUE THREAD

**Issue by nickurt** [TeamGnome/WUTest#11]
The Win10Labs is now hardcoded to '[https://buildfeed.net/api/getwin10labs](https://github.com/TeamGnome/WUTest/blob/master/WUTest/LabStore.cs#L32)', but it's not possible to use a custom xml (from web).

It is possible to add an new option to use custom xml (from web)?

**Comment by AirportsFan** [comment]
An update version of WUDetector has been published. Here is the currently latest release compile:
https://github.com/TeamGnome/WUTest/blob/master/WUTest/bin/Debug/WUDetector.exe

Be sure to let us know about any inquiries regarding it.

**Comment by nickurt** [comment]
Looks like only https is supported now, can you make it working for http too?

**Comment by nickurt** [comment]
Regex

    (http(s)?:\/\/)([a-z_-]+).([a-z]+){2,6}([a-z./-]+)

Matched with the following patterns

    http://ms-vnext.net
	https://ms-vnext.net

	http://www.ms-vnext.net
	https://www.ms-vnext.net

	http://ms-vnext.net/feed.xml
	http://ms-vnext.net/args/args/args/feed.xml
	https://ms-vnext.net/feed.xml
	https://ms-vnext.net/args/args/args/feed.xml

	http://www.ms-vnext.net/feed.xml
	http://www.ms-vnext.net/args/args/args/feed.xml
	https://www.ms-vnext.net/feed.xml
	https://www.ms-vnext.net/args/args/args/feed.xml

	http://buildfeed.net
	https://buildfeed.net

**Comment by nickurt** [comment]
Works
