### ISSUE TITLE
WUTest throws an exception if wuauserv is already running

### ISSUE THREAD

**Issue by SrcFlux** [TeamGnome/WUTest#4]
<pre>Unbehandelte Ausnahme: System.InvalidOperationException: Der Dienst wuauserv kann nicht auf dem Computer . gestartet werden. ---> System.ComponentModel.Win32Exception: Es wird bereits eine Instanz des Dienstes ausgeführt
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.ServiceProcess.ServiceController.Start(String[] args)
   bei WUDetectorScope.Program.RetrieveESDFilesFromDataStore()
   bei WUDetectorScope.Program.SeekArguments(String[] arguments)
   bei WUDetectorScope.Program.Main(String[] args)</pre>

![unbenannt](https://cloud.githubusercontent.com/assets/8874705/6244800/298ee9ae-b758-11e4-8c4c-b57126422e6b.png)

**Comment by AirportsFan** [comment]
Hello Daniel. I tried on Windows 10 and it was working fine here, as the procedure should show "Stopping Windows Update service..." then stop wuauserv service, but as I understood from the error it's trying to create a new instance?

Mind posting the script you're using Daniel?

**Comment by SrcFlux** [comment]
I am running WUDetector from a batch file with <code>/GetFiles</code> and <code>/NoAction</code> args, but that's not relevant to the issue I think.

From what I can see the issue with the service lies here:

<pre>            if (restartSvc)
            {
                Console.Write("\r\nRerunning Windows Update Service...");
                service.Start();
                service.WaitForStatus(ServiceControllerStatus.Running, timeout);
                Console.WriteLine("Done.");
            }</pre>

Sometimes, the Windows Update Service is being restarted automatically. If that happens before WUDetector tries to restart the service, that exception is being thrown. A simple check whether the service is already running should solve the issue.

**Comment by AirportsFan** [comment]
If it's from there it'd at least show "Rerunning Windows Update Service..." before the exception Daniel.

I'll update that code though to check whether the service is running or not prior to re-running it.

**Comment by AirportsFan** [comment]
I've updated the binaries. You may use the debug one so when it throws the exception again we can know from where is the issue on this link:
https://github.com/TeamGnome/WUTest/blob/master/WUTest/bin/Debug/WUDetector10.exe

Let me know if it helped.

**Comment by SrcFlux** [comment]
I didn't experience any problems related to this issue again so far, seems to be fixed now :+1:
