### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by SrcFlux** [TeamGnome/WUTest#5]
![unbenannt](https://cloud.githubusercontent.com/assets/8874705/6471518/d97d2d10-c1eb-11e4-8854-041150e92d07.png)

<pre>Unbehandelte Ausnahme: System.IndexOutOfRangeException: An der Position 0 befindet sich keine Zeile.
   bei System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   bei System.Data.DataRowCollection.get_Item(Int32 index)
   bei WUDetectorScope.Program.RetrieveESDFilesFromDataStore()
   bei WUDetectorScope.Program.SeekArguments(String[] arguments)
   bei WUDetectorScope.Program.Main(String[] args)</pre>

Translated stack:
<pre>Unhandled exception: System.IndexOutOfRangeException: There is no row at position 0.
   at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at System.Data.DataRowCollection.get_Item(Int32 index)
   at WUDetectorScope.Program.RetrieveESDFilesFromDataStore()
   at WUDetectorScope.Program.SeekArguments(String[] arguments)
   at WUDetectorScope.Program.Main(String[] args)</pre>

I'm running WUTest with these arguments: <code>WuDetector /Debug /NoAction /GetFiles > BuildList.%PROCESSOR_ARCHITECTURE%.txt</code>

The exception is being thrown on build 9926 in both, x86 and amd64 flavours. 

I am not really sure what is causing this behaviour, I haven't seen this exception before today...

**Comment by AirportsFan** [comment]
The issue is weird - RetrieveESDFilesFromDataStore is completely covered with try and catch code, in a way to prevent throwing .NET exceptions. The issue seem to have occured while initializing DataRows, which is covered in try/catch too.

Also, since you're using /debug, you should at least see "RetrieveESDFilesFromDataStore: Administrative privileges met." when it's done checking for admin privileges, but it's jumping right to reading DataRows?

Very sorry about your trouble Daniel. It sounds like 9926 or some TSR programs is messing up the execution of the program. I'll look into it though and see what I can do about it.

**Comment by SrcFlux** [comment]
Nope, I am not seeing that line here.

It seems this exception is being thrown if DataStore is still in use by Windows Update.. Maybe checking/making sure the corresponding files are not locked might help ...?

**Comment by AirportsFan** [comment]
It can't be that in any way. WUDetector will ensure that the service is stopped completely, or it'll immediately terminate itself if it can't stop wuauserv. Also providing you ran regular check before it, hence wuauserv was in running state (i.e. not trying to stop or run).

However, seems the main issue was in the following line:
int curBuildNumber = Convert.ToInt32( dTable.Rows[0]["File"].ToString().Substring(0, dTable.Rows[0]["File"].ToString().IndexOf(".0")));

As for some reason it was not in try/catch area.

I updated the source code. Binaries are on their way now to compile on Win10 VM.

**Comment by AirportsFan** [comment]
Source has been compiled. Available in its regular location at: https://github.com/TeamGnome/WUTest/blob/master/WUTest/bin/Debug/WUDetector10.exe

Hopefully it will fix the issue now. Let me know Daniel for any inquiry.

**Comment by SrcFlux** [comment]
Seems to be fixed now. :+1:
