### ISSUE TITLE
WUTest seems to report the wrong date/time

### ISSUE THREAD

**Issue by SrcFlux** [TeamGnome/WUTest#6]
Either Microsoft's got a time machine now, or WUTest reports the wrong date for the ESDs.

**Comment by AirportsFan** [comment]
Guess it's from Microsoft's side. We might not be able to do anything about it atm.

If any other builds had the same issue, let me know Daniel and will look into it.

**Comment by nickurt** [comment]
21/03/2015 11:17:55 -> 10046.0.150321-1600.fbl_kpg_CLIENTENTERPRISE_VOL_x86fre_en-us.esd 
    21/03/2015 03:52:11 -> 10046.0.150321-0352.fbl_ppi_CLIENTPRO_RET_x64fre_en-us.esd
    21/03/2015 03:49:16 -> 10046.0.150321-0352.fbl_ppi_CLIENTENTERPRISE_VOL_x64fre_en-us.esd

**Comment by AirportsFan** [comment]
Yes, it looks like either ESD storage system at Microsoft is now moved to another location with different timezone, or something like that? Can't be sure for now until we do further checking.

Probably a comparison of old correct results with these would help discovering the change happened.

**Comment by nickurt** [comment]
20150321-1217	10046.0.150321-1600.fbl_kpg_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20150319-1256	10045.0.150319-1527.winmain_CLIENTPRO_RET_x86fre_en-us.esd
	20150318-1159	10044.0.150318-1600.fbl_lad_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20150317-1223	10043.0.150317-1600.fbl_lad_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20150317-1156	10043.0.150317-1425.winmain_CLIENTENTERPRISE_VOL_x86fre_zh-cn.esd
	20150317-1130	10043.0.150317-1425.winmain_CLIENTPRO_RET_x86fre_zh-cn.esd
	20150317-1013	10043.0.150317-1425.winmain_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20150317-1012	10043.0.150317-1425.winmain_CLIENTPRO_RET_x86fre_en-us.esd
	20150316-1152	10042.0.150316-1457.winmain_CLIENTENTERPRISE_VOL_x86fre_zh-cn.esd
	20150316-1147	10042.0.150316-1457.winmain_CLIENTPRO_RET_x86fre_zh-cn.esd
	20150316-1030	10042.0.150316-1457.winmain_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20150316-1023	10042.0.150316-1457.winmain_CLIENTPRO_RET_x86fre_en-us.esd
	20150310-1233	10038.0.150310-1453.winmain_CLIENTENTERPRISE_VOL_x86fre_zh-cn.esd
	20150310-1226	10038.0.150310-1453.winmain_CLIENTPRO_RET_x86fre_zh-cn.esd
	20150310-1131	10038.0.150310-1453.winmain_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20150310-1115	10038.0.150310-1453.winmain_CLIENTPRO_RET_x86fre_en-us.esd
	20150309-1201	10037.0.150309-1510.winmain_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20150309-1101	10037.0.150309-1510.winmain_CLIENTPRO_RET_x86fre_en-us.esd
	20150304-1411	10034.0.150304-1440.winmain_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20150304-1405	10034.0.150304-1440.winmain_CLIENTPRO_RET_x86fre_en-us.esd
	20141203-2337	9902.0.141203-2339.fbl_cortana_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20141201-1213	9900.0.141201-1500.winmain_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
	20141201-1151	9900.0.141201-1500.winmain_CLIENTPRO_RET_x86fre_en-us.esd

**Comment by nickurt** [comment]
2015-03-22 10:51	10046.0.150322-1600.fbl_kpg_CLIENTENTERPRISE_VOL_x86fre_en-us.esd
    2015-03-22 09:32	10046.0.150322-1218.fbl_opt_CLIENTENTERPRISE_VOL_x64fre_en-us.esd

**Comment by nickurt** [comment]
Closed, since Microsoft don't pushed with wrong dateTime stamps anymore ...
