### ISSUE TITLE
Application crashes when retrieving ESD files with a 5-digit revision number

### ISSUE THREAD

**Issue by SrcFlux** [TeamGnome/WUTest#7]
![image](https://cloud.githubusercontent.com/assets/8874705/8518568/933200fa-23cb-11e5-9db9-9c9a5d9045de.png)

Issue seems to be related to these lines:
https://github.com/TeamGnome/WUTest/blob/3a0addc6e663fc00c8b526adb515346e55665531/WUTest/DataStore.cs#L136
https://github.com/TeamGnome/WUTest/blob/3a0addc6e663fc00c8b526adb515346e55665531/WUTest/DataStore.cs#L151
https://github.com/TeamGnome/WUTest/blob/3a0addc6e663fc00c8b526adb515346e55665531/WUTest/DataStore.cs#L167

**Comment by LucasM99** [comment]
Thanks for reporting this bug, I've taken a look at it and submitted a Pull Request, it should be fixed soon :)

**Comment by SrcFlux** [comment]
Works fine now, thanks :+1:
